version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: travellist
        container_name: travellist-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - travellist

    mysql:
        image: mysql:5.6.51
        ports:
            - '8005:3306'
        environment:
            - MYSQL_HOST=mysql
            - MYSQL_DATABASE=test
            - MYSQL_ROOT_PASSWORD=password
            - TZ=Europe/Paris

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8004:80'
        environment:
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=password
            - MYSQL_ROOT_PASSWORD=password
        depends_on:
            - mysql


    nginx:
        image: nginx:alpine
        container_name: travellist-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - travellist

networks:
    travellist:
        driver: bridge
